<?php

namespace MyJobs\CoreBundle\Repository;
use MyJobs\CoreBundle\Entity\Application;

/**
 * ApplicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return Application[]
     */
    public function findMyApplications($user)
    {
        return $this
            ->createQueryBuilder('a')
            ->where('a.user = :user')
            ->setParameter('user', $user)
            ->getQuery()
            ->getResult()
        ;
    }
}
