<?php

namespace MyJobs\CoreBundle\Repository;
use MyJobs\CoreBundle\Entity\Appointment;

/**
 * AppointmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppointmentRepository extends \Doctrine\ORM\EntityRepository
{
}
