<?php

namespace MyJobs\CoreBundle\Repository;
use MyJobs\CoreBundle\Entity\Company;

/**
 * CompanyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyRepository extends \Doctrine\ORM\EntityRepository
{
    public function myCompaniesFromQB($user)
    {
        return $this
            ->createQueryBuilder('u')
            ->where('u.user = :user')
            ->setParameter('user', $user)
        ;
    }

    /**
     * @return Company[]
     */
    public function findMyCompanies($user)
    {
        return $this
            ->createQueryBuilder('c')
            ->where('c.user = :user')
            ->setParameter('user', $user)
            ->getQuery()
            ->getResult()
        ;
    }
}
