services:
    twig.extension:
        class: JG\CoreBundle\Twig\Extension\TwigExtension
        tags:
            - { name: twig.extension }
    alert.extension:
        class: JG\CoreBundle\Twig\Extension\AlertExtension
        arguments: ['@service_container', '@security.token_storage']
        tags:
            - { name: twig.extension }