services:
    twig.extension:
        class: JG\CoreBundle\Twig\Extension\TwigExtension
        tags:
            - { name: twig.extension }
    counter.extension:
        class: JG\CoreBundle\Twig\Extension\CounterExtension
        arguments: ['@service_container', '@security.token_storage']
        tags:
            - { name: twig.extension }
    app.mailer:
        class: JG\CoreBundle\Services\Mailer\NotificationMailer
        arguments: ['@mailer','@templating']
    app.alert.application:
        class: JG\CoreBundle\Services\Alert\ApplicationAlert
        arguments: ['@doctrine.orm.entity_manager', '@security.token_storage']
    app.alert.appointment:
        class: JG\CoreBundle\Services\Alert\AppointmentAlert
        arguments: ['@doctrine.orm.entity_manager', '@security.token_storage']
    app.export:
        class: JG\CoreBundle\Services\Export\ExportDatas
        arguments: ['@doctrine.orm.entity_manager']