services:
    twig.extension:
        class: JG\CoreBundle\Twig\Extension\TwigExtension
        tags:
            - { name: twig.extension }
    counter.extension:
        class: JG\CoreBundle\Twig\Extension\CounterExtension
        arguments: ['@service_container', '@security.token_storage']
        tags:
            - { name: twig.extension }
    app.mailer:
        class: JG\CoreBundle\Services\Mailer\NotificationMailer
        arguments: ['@mailer','@templating']
    app.alert:
        class: JG\CoreBundle\Services\Alert\NotificationAlert
        arguments: ['@doctrine.orm.entity_manager', '@security.token_storage']