myjobs_front:
    resource: "@MyJobsFrontBundle/Controller/"
    type:     annotation

myjobs_admin:
    resource: "@MyJobsAdminBundle/Controller/Admin/"
    type:     annotation

myjobs_account:
    resource: "@MyJobsAdminBundle/Controller/Account/"
    type:     annotation

myjobs_user:
    resource: "@MyJobsUserBundle/Controller/"
    type:     annotation

myjobs_core:
    resource: "@MyJobsCoreBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"