jg_front:
    resource: "@JGFrontBundle/Controller/"
    type:     annotation

jg_admin:
    resource: "@JGAdminBundle/Controller/"
    type:     annotation

jg_user:
    resource: "@JGUserBundle/Controller/"
    type:     annotation

jg_core:
    resource: "@JGCoreBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"