jg_front:
    resource: "@JGFrontBundle/Controller/"
    type:     annotation

jg_admin:
    resource: "@JGAdminBundle/Controller/Admin/"
    type:     annotation
    prefix:   /admin

jg_account:
    resource: "@JGAdminBundle/Controller/Account/"
    type:     annotation
    prefix:   /account

jg_user:
    resource: "@JGUserBundle/Controller/"
    type:     annotation

jg_core:
    resource: "@JGCoreBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"