<?php

namespace JG\CoreBundle\Repository;

use JG\CoreBundle\Entity\Company;

/**
 * CompanyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyRepository extends \Doctrine\ORM\EntityRepository
{
    public function findCount()
    {
        return $this
            ->createQueryBuilder('c')
            ->select('COUNT(c)')
            ->getQuery()
            ->getSingleScalarResult()
        ;
    }

    public function myCompaniesFromQB($user)
    {
        return $this
            ->createQueryBuilder('u')
            ->where('u.user = :user')
            ->setParameter('user', $user)
        ;
    }

    /**
     * @return Company[]
     */
    public function findMyCompanies($user)
    {
        return $this
            ->createQueryBuilder('c')
            ->where('c.user = :user')
            ->setParameter('user', $user)
            ->getQuery()
            ->getResult()
        ;
    }

    /**
     * @return Company[]
     */
    public function findMyLastCompanies($user)
    {
        return $this
            ->createQueryBuilder('c')
            ->where('c.user = :user')
            ->setParameter('user', $user)
            ->setMaxResults(3)
            ->getQuery()
            ->getResult()
        ;
    }

    public function countMyCompanies($user)
    {
        return $this
            ->createQueryBuilder('c')
            ->select('COUNT(c)')
            ->where('c.user = :user')
            ->setParameter('user', $user)
            ->getQuery()
            ->getSingleScalarResult();
    }

    public function exportMyCompanies($user, $options = null)
    {
        $qb = $this
            ->createQueryBuilder('c')
            ->where('c.user = :user')
            ->setParameter('user', $user)
        ;
        if ($options) {
            $start = new \DateTime($options['start']->format("Y-m-d"));
            $end   = new \DateTime($options['end']->format("Y-m-d"));
            $qb = $qb
                ->andWhere('c.createdAt >= :start')
                ->setParameter('start', $start)
                ->andWhere('c.createdAt <= :end')
                ->setParameter('end', $end)
            ;
        }
        $qb = $qb
            ->getQuery()
            ->iterate()
        ;
        return $qb;
    }

    /**
     * @return Company[]
     */
    public function exportAllCompanies()
    {
        return $this
            ->createQueryBuilder('c')
            ->getQuery()
            ->iterate()
        ;
    }
}
