<?php

namespace JG\CoreBundle\Repository;

/**
 * ContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactRepository extends \Doctrine\ORM\EntityRepository
{
    public function findCount()
    {
        return $this
            ->createQueryBuilder('c')
            ->select('COUNT(c)')
            ->getQuery()
            ->getSingleScalarResult()
        ;
    }

    public function countUnread()
    {
        return $this
            ->createQueryBuilder('c')
            ->select('COUNT(c)')
            ->andWhere('c.viewed = 0')
            ->getQuery()
            ->getSingleScalarResult()
        ;
    }
}
