<?php

namespace JG\CoreBundle\Repository;

/**
 * ContractRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContractRepository extends \Doctrine\ORM\EntityRepository
{
    public function findCount()
    {
        return
            $this->_em
                ->createQuery('SELECT count(c) FROM JGCoreBundle:Contract c')
                ->getSingleScalarResult();
    }
}
