<?php

namespace JG\CoreBundle\Repository;

use JG\CoreBundle\Entity\Preference;

/**
 * PreferenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PreferenceRepository extends \Doctrine\ORM\EntityRepository
{
    public function myPreferencesFromQB($user)
    {
        return $this
            ->createQueryBuilder('p')
            ->where('p.user = :user')
            ->setParameter('user', $user)
            ;
    }

    /**
     * @return Preference[]
     */
    public function findMyPreferences($user)
    {
        return $this
            ->createQueryBuilder('p')
            ->where('p.user = :user')
            ->setParameter('user', $user)
            ->getQuery()
            ->getResult()
        ;
    }
}
