<?php

namespace JG\CoreBundle\Repository;

/**
 * RelaunchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RelaunchRepository extends \Doctrine\ORM\EntityRepository
{
}
