<?php

namespace JG\CoreBundle\Repository;

/**
 * StatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatusRepository extends \Doctrine\ORM\EntityRepository
{
    public function findCount()
    {
        return
            $this->_em
                ->createQuery('SELECT count(s) FROM JGCoreBundle:Status s')
                ->getSingleScalarResult();
    }
}
